"""
Instrucciones para configurar Hugging Face API
"""
print("=== CONFIGURACIÓN DE HUGGING FACE ===")
print()
print("Para usar la API oficial de Hugging Face:")
print()
print("1. Ve a: https://huggingface.co/settings/tokens")
print("2. Haz clic en 'New token'")
print("3. Dale un nombre (ej: 'mi-proyecto-tienda')")
print("4. Selecciona 'Read' como permisos")
print("5. Haz clic en 'Generate a token'")
print("6. Copia el token (empieza con 'hf_')")
print()
print("7. Abre el archivo backend/.env")
print("8. Agrega esta línea:")
print("   HUGGINGFACE_API_KEY=tu_token_aqui")
print()
print("9. Reinicia el servidor backend")
print("10. Prueba con: curl http://localhost:8000/huggingface/status")
print()
print("Una vez configurado, el análisis de imágenes funcionará correctamente")
print("y podrás obtener descripciones reales de las imágenes en lugar de")
print("análisis básicos.")
