"""Add MFA and user enhancement fields

Revision ID: 1ba79099ddaf
Revises: 5a37858ff207
Create Date: 2025-10-21 11:40:06.180107

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1ba79099ddaf'
down_revision = '5a37858ff207'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar columnas con valores por defecto para usuarios existentes
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('mfa_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Actualizar usuarios existentes con valores por defecto
    op.execute("UPDATE users SET active = true WHERE active IS NULL")
    op.execute("UPDATE users SET mfa_enabled = false WHERE mfa_enabled IS NULL")
    
    # Hacer las columnas NOT NULL después de actualizar
    op.alter_column('users', 'active', nullable=False)
    op.alter_column('users', 'mfa_enabled', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'active')
    # ### end Alembic commands ###
