"""Add updated_at column to chats table

Revision ID: 5a37858ff207
Revises: add_balance_to_users
Create Date: 2025-10-21 09:08:26.270259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision = '5a37858ff207'
down_revision = 'add_balance_to_users'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('ix_chat_messages_id', table_name='chat_messages')
    op.add_column('chats', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('ix_chats_id', table_name='chats')
    op.drop_index('ix_order_items_id', table_name='order_items')
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('ix_orders_id', table_name='orders')
    op.drop_index('ix_product_images_id', table_name='product_images')
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=True)
    op.alter_column('products', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_index('ix_products_id', table_name='products')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('users', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('ix_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.drop_column('users', 'updated_at')
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    op.alter_column('products', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('products', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.create_index('ix_product_images_id', 'product_images', ['id'], unique=False)
    op.create_index('ix_orders_id', 'orders', ['id'], unique=False)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('orders', 'updated_at')
    op.create_index('ix_order_items_id', 'order_items', ['id'], unique=False)
    op.create_index('ix_chats_id', 'chats', ['id'], unique=False)
    op.alter_column('chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('chats', 'updated_at')
    op.create_index('ix_chat_messages_id', 'chat_messages', ['id'], unique=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('chat_messages', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('chat_messages', 'updated_at')
    # ### end Alembic commands ###
