"""Add email verification and password reset fields

Revision ID: 7ac6d5508b24
Revises: a2f9d720b129
Create Date: 2025-10-22 09:04:44.341782

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7ac6d5508b24'
down_revision = 'a2f9d720b129'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar columnas con valores por defecto para usuarios existentes
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_confirmation_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('password_reset_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires', sa.DateTime(), nullable=True))
    
    # Actualizar usuarios existentes con valores por defecto
    op.execute("UPDATE users SET email_verified = true WHERE email_verified IS NULL")
    
    # Hacer la columna NOT NULL después de actualizar
    op.alter_column('users', 'email_verified', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'email_confirmation_token')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
