"""Rename hashed_password to password_hash

Revision ID: a2f9d720b129
Revises: 1ba79099ddaf
Create Date: 2025-10-21 11:50:26.851418

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a2f9d720b129'
down_revision = '1ba79099ddaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar nueva columna como nullable primero
    op.add_column('users', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Copiar datos de hashed_password a password_hash
    op.execute("UPDATE users SET password_hash = hashed_password WHERE hashed_password IS NOT NULL")
    
    # Hacer la columna NOT NULL después de copiar los datos
    op.alter_column('users', 'password_hash', nullable=False)
    
    # Eliminar la columna antigua
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
